"""Static registry for shell templates and curated snippets."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping


DATA_DIR = Path(__file__).resolve().parent / "data"
PLACEHOLDER_620X320 = "https://dummyimage.com/620x320/00175a/ffffff.png&text=AMEX+Hero"
PLACEHOLDER_620X620 = "https://dummyimage.com/620x620/00175a/ffffff.png&text=AMEX+Campaign"
PLACEHOLDER_305X200 = "https://dummyimage.com/305x200/f4f4f4/00175a.png&text=AMEX+Module"
PLACEHOLDER_620X250 = "https://dummyimage.com/620x250/000000/ffffff.png&text=Centurion"
PLACEHOLDER_60 = "https://dummyimage.com/60x60/006fcf/ffffff.png&text=AMEX"
PLACEHOLDER_80 = "https://dummyimage.com/80x50/3d3d3d/ffffff.png&text=CARD"
PLACEHOLDER_TAGLINE = "https://dummyimage.com/150x30/ffffff/3d3d3d.png&text=American+Express"
PLACEHOLDER_TAGLINE_DARK = "https://dummyimage.com/150x30/000000/ffffff.png&text=Centurion"
PLACEHOLDER_TAGLINE_WIDE = "https://dummyimage.com/620x80/ffffff/3d3d3d.png&text=No+vivas+la+vida+sin+ella"
PLACEHOLDER_TAGLINE_WIDE_MOBILE = "https://dummyimage.com/620x80/ffffff/3d3d3d.png&text=No+vivas+la+vida+sin+ella+Mobile"
DEFAULT_LEGAL_HTML = "<p style=\"margin:0;color:#53565A;font-size:13px;line-height:18px;font-family:HelveticaNeue, Helvetica Neue Regular, Helvetica, Arial, sans-serif;\">Legales pendientes de definir para este envío.</p>"
DEFAULT_CENTURION_LEGAL_HTML = "<p style=\"margin:0;color:#CCCCCC;font-size:12px;line-height:18px;font-family:HelveticaNeue, Helvetica Neue Regular, Helvetica, Arial, sans-serif;\">Legales pendientes de definir para este envío Centurion.</p>"


@dataclass(frozen=True)
class SnippetAsset:
    key: str
    path: Path
    source_id: str


@dataclass(frozen=True)
class ComponentDefinition:
    api_id: str
    slot: str
    compose_type: str
    source_ids: tuple[str, ...]
    snippet_keys: tuple[str, ...]
    required_props: tuple[str, ...] = ()
    defaults: Mapping[str, Any] = field(default_factory=dict)
    repeatable: bool = True
    auto_separator_before: str | None = None
    auto_separator_after: str | None = None
    compatible_families: tuple[str, ...] = ()
    context_builder: str | None = None


@dataclass(frozen=True)
class FamilyDefinition:
    family_id: str
    shell_path: Path
    shell_defaults: Mapping[str, Any]
    snippets: Mapping[str, SnippetAsset]
    components: Mapping[str, ComponentDefinition]


def _snippet(family: str, key: str, filename: str, source_id: str) -> SnippetAsset:
    return SnippetAsset(
        key=key,
        path=DATA_DIR / "snippets" / family / filename,
        source_id=source_id,
    )


MARIGOLD_V42_SNIPPETS = MappingProxyType(
    {
        "separator": _snippet("marigold-v4.2", "separator", "separator.html", "SEPARATOR"),
        "ph01": _snippet("marigold-v4.2", "ph01", "ph01.html", "PH01-v4.2"),
        "brand_panel": _snippet("marigold-v4.2", "brand_panel", "brand-panel.html", "Consumer Default-v4.2"),
        "brand_panel_merchant_shot_travel_agst25": _snippet("marigold-v4.2", "brand_panel_merchant_shot_travel_agst25", "brand-panel-merchant-shot-travel-agst25.html", "Consumer Default-v4.2"),
        "hb03": _snippet("marigold-v4.2", "hb03", "hb03.html", "HB03-v4.2"),
        "hb08": _snippet("marigold-v4.2", "hb08", "hb08.html", "HB08-v4.2"),
        "hb15": _snippet("marigold-v4.2", "hb15", "hb15.html", "HB15-v4.2"),
        "hb16": _snippet("marigold-v4.2", "hb16", "hb16.html", "HB16-v4.2"),
        "hb18": _snippet("marigold-v4.2", "hb18", "hb18.html", "HB18-v4.2"),
        "hb18_merchant_shot_travel_agst25": _snippet("marigold-v4.2", "hb18_merchant_shot_travel_agst25", "hb18-merchant-shot-travel-agst25.html", "HB18-v4.2"),
        "hb21": _snippet("marigold-v4.2", "hb21", "hb21.html", "HB21-v4.2"),
        "im03": _snippet("marigold-v4.2", "im03", "im03.html", "IM03-v4.2"),
        "tm01": _snippet("marigold-v4.2", "tm01", "tm01.html", "TM01-v4.2"),
        "tm03": _snippet("marigold-v4.2", "tm03", "tm03.html", "TM03-v4.2"),
        "tm03_merchant_shot_travel_agst25": _snippet("marigold-v4.2", "tm03_merchant_shot_travel_agst25", "tm03-merchant-shot-travel-agst25.html", "TM03-v4.2"),
        "tm04": _snippet("marigold-v4.2", "tm04", "tm04.html", "TM04-v4.2"),
        "tm04_merchant_shot_travel_agst25_agencias": _snippet("marigold-v4.2", "tm04_merchant_shot_travel_agst25_agencias", "tm04-merchant-shot-travel-agst25-agencias.html", "TM04-v4.2"),
        "tm04_merchant_shot_travel_agst25_compras": _snippet("marigold-v4.2", "tm04_merchant_shot_travel_agst25_compras", "tm04-merchant-shot-travel-agst25-compras.html", "TM04-v4.2"),
        "tm04_merchant_shot_travel_agst25_spa": _snippet("marigold-v4.2", "tm04_merchant_shot_travel_agst25_spa", "tm04-merchant-shot-travel-agst25-spa.html", "TM04-v4.2"),
        "tm04_merchant_shot_travel_agst25_hashtag": _snippet("marigold-v4.2", "tm04_merchant_shot_travel_agst25_hashtag", "tm04-merchant-shot-travel-agst25-hashtag.html", "TM04-v4.2"),
        "tm17": _snippet("marigold-v4.2", "tm17", "tm17.html", "TM17-v4.2"),
        "fm05": _snippet("marigold-v4.2", "fm05", "fm05.html", "FM05-v4.2"),
        "fm01": _snippet("marigold-v4.2", "fm01", "fm01.html", "FM01-v4.2"),
        "tm06": _snippet("marigold-v4.2", "tm06", "tm06.html", "TM06-v4.2"),
        "fm02": _snippet("marigold-v4.2", "fm02", "fm02.html", "FM02"),
        "fm03": _snippet("marigold-v4.2", "fm03", "fm03.html", "FM03-v4.2"),
        "fm04": _snippet("marigold-v4.2", "fm04", "fm04.html", "FM04-v4.2"),
        "fm04_merchant_shot_travel_agst25": _snippet("marigold-v4.2", "fm04_merchant_shot_travel_agst25", "fm04-merchant-shot-travel-agst25.html", "FM04-v4.2"),
        "brand_panel_merchant_newsletter_dic25": _snippet("marigold-v4.2", "brand_panel_merchant_newsletter_dic25", "brand-panel-merchant-newsletter-dic25.html", "Consumer Default-v4.2"),
        "fm02_merchant_newsletter_dic25": _snippet("marigold-v4.2", "fm02_merchant_newsletter_dic25", "fm02-merchant-newsletter-dic25.html", "FM02"),
        "hb03_merchant_newsletter_dic25": _snippet("marigold-v4.2", "hb03_merchant_newsletter_dic25", "hb03-merchant-newsletter-dic25.html", "HB03-v4.2"),
        "tm04_merchant_newsletter_dic25_intro": _snippet("marigold-v4.2", "tm04_merchant_newsletter_dic25_intro", "tm04-merchant-newsletter-dic25-intro.html", "TM04-v4.2"),
        "tm01_merchant_newsletter_dic25_compras": _snippet("marigold-v4.2", "tm01_merchant_newsletter_dic25_compras", "tm01-merchant-newsletter-dic25-compras.html", "TM01-v4.2"),
        "hb08_merchant_newsletter_dic25_compras": _snippet("marigold-v4.2", "hb08_merchant_newsletter_dic25_compras", "hb08-merchant-newsletter-dic25-compras.html", "HB08-v4.2"),
        "tm01_merchant_newsletter_dic25_gastronomia": _snippet("marigold-v4.2", "tm01_merchant_newsletter_dic25_gastronomia", "tm01-merchant-newsletter-dic25-gastronomia.html", "TM01-v4.2"),
        "hb08_merchant_newsletter_dic25_gastronomia": _snippet("marigold-v4.2", "hb08_merchant_newsletter_dic25_gastronomia", "hb08-merchant-newsletter-dic25-gastronomia.html", "HB08-v4.2"),
        "tm01_merchant_newsletter_dic25_hoteles": _snippet("marigold-v4.2", "tm01_merchant_newsletter_dic25_hoteles", "tm01-merchant-newsletter-dic25-hoteles.html", "TM01-v4.2"),
        "tm04_merchant_newsletter_dic25_hoteles": _snippet("marigold-v4.2", "tm04_merchant_newsletter_dic25_hoteles", "tm04-merchant-newsletter-dic25-hoteles.html", "TM04-v4.2"),
        "hb08_merchant_newsletter_dic25_hoteles": _snippet("marigold-v4.2", "hb08_merchant_newsletter_dic25_hoteles", "hb08-merchant-newsletter-dic25-hoteles.html", "HB08-v4.2"),
        "tm04_merchant_newsletter_dic25_cta": _snippet("marigold-v4.2", "tm04_merchant_newsletter_dic25_cta", "tm04-merchant-newsletter-dic25-cta.html", "TM04-v4.2"),
        "fm04_merchant_newsletter_dic25": _snippet("marigold-v4.2", "fm04_merchant_newsletter_dic25", "fm04-merchant-newsletter-dic25.html", "FM04-v4.2"),
        "brand_panel_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "brand_panel_merchant_shot_deporte_dic25", "brand-panel-merchant-shot-deporte-dic25.html", "Consumer Default-v4.2"),
        "hb18_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "hb18_merchant_shot_deporte_dic25", "hb18-merchant-shot-deporte-dic25.html", "HB18-v4.2"),
        "tm04_merchant_shot_deporte_dic25_intro": _snippet("marigold-v4.2", "tm04_merchant_shot_deporte_dic25_intro", "tm04-merchant-shot-deporte-dic25-intro.html", "TM04-v4.2"),
        "tm04_merchant_shot_deporte_dic25_clubs": _snippet("marigold-v4.2", "tm04_merchant_shot_deporte_dic25_clubs", "tm04-merchant-shot-deporte-dic25-clubs.html", "TM04-v4.2"),
        "hb08_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "hb08_merchant_shot_deporte_dic25", "hb08-merchant-shot-deporte-dic25.html", "HB08-v4.2"),
        "tm04_merchant_shot_deporte_dic25_closing": _snippet("marigold-v4.2", "tm04_merchant_shot_deporte_dic25_closing", "tm04-merchant-shot-deporte-dic25-closing.html", "TM04-v4.2"),
        "fm05_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "fm05_merchant_shot_deporte_dic25", "fm05-merchant-shot-deporte-dic25.html", "FM05-v4.2"),
        "fm02_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "fm02_merchant_shot_deporte_dic25", "fm02-merchant-shot-deporte-dic25.html", "FM02"),
        "fm04_merchant_shot_deporte_dic25": _snippet("marigold-v4.2", "fm04_merchant_shot_deporte_dic25", "fm04-merchant-shot-deporte-dic25.html", "FM04-v4.2"),
    }
)

MARIGOLD_V42_COMPONENTS = MappingProxyType(
    {
        "H01": ComponentDefinition(
            api_id="H01",
            slot="header",
            compose_type="composite",
            source_ids=("PH01-v4.2", "Consumer Default-v4.2"),
            snippet_keys=("ph01", "brand_panel"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            context_builder="marigold_v42_header",
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
                "logoUrl": PLACEHOLDER_60,
                "logoAlt": "American Express",
                "accountSuffix": "{(LAST_5)}",
                "greetingName": "{(FULLNAME)}",
                "loginUrl": "https://www.americanexpress.com/es-ar/account/login?email_consumer",
                "loginLabel": "Mi cuenta",
                "showGreeting": True,
                "showLogin": True,
                "showMemberSince": True,
                "brandVariant": "consumer",
            },
        ),
        "H02": ComponentDefinition(
            api_id="H02",
            slot="header",
            compose_type="composite",
            source_ids=("PH01-v4.2", "Consumer Default-v4.2"),
            snippet_keys=("ph01", "brand_panel_merchant_shot_travel_agst25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
            },
        ),
        "H03": ComponentDefinition(
            api_id="H03",
            slot="header",
            compose_type="composite",
            source_ids=("PH01-v4.2", "Consumer Default-v4.2"),
            snippet_keys=("ph01", "brand_panel_merchant_newsletter_dic25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
            },
        ),
        "H04": ComponentDefinition(
            api_id="H04",
            slot="header",
            compose_type="composite",
            source_ids=("PH01-v4.2", "Consumer Default-v4.2"),
            snippet_keys=("ph01", "brand_panel_merchant_shot_deporte_dic25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
            },
        ),
        "B01": ComponentDefinition(
            api_id="B01",
            slot="body",
            compose_type="single",
            source_ids=("HB03-v4.2",),
            snippet_keys=("hb03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bgColor": "#00175A",
                "textColor": "#FFFFFF",
                "headline": "Descubrí un beneficio especial",
                "description": "Completá este módulo con contenido personalizado o usá este bloque como placeholder visual.",
                "imageUrl": PLACEHOLDER_620X320,
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
            },
        ),
        "B02": ComponentDefinition(
            api_id="B02",
            slot="body",
            compose_type="single",
            source_ids=("HB08-v4.2",),
            snippet_keys=("hb08",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            context_builder="paired_items",
            defaults={
                "items": (
                    {
                        "title": "Beneficio 1",
                        "description": "Descripción del beneficio.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "Conocé más",
                    },
                    {
                        "title": "Beneficio 2",
                        "description": "Descripción del beneficio.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "Conocé más",
                    },
                ),
            },
        ),
        "B03": ComponentDefinition(
            api_id="B03",
            slot="body",
            compose_type="single",
            source_ids=("HB15-v4.2",),
            snippet_keys=("hb15",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bgColor": "#FFFFFF",
                "headlineBgColor": "#00175A",
                "imageDesktopUrl": PLACEHOLDER_620X320,
                "imageMobileUrl": PLACEHOLDER_620X320,
                "headline": "Hero principal",
                "description": "Este hero usa valores por defecto hasta que envíes datos específicos.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
            },
        ),
        "B04": ComponentDefinition(
            api_id="B04",
            slot="body",
            compose_type="single",
            source_ids=("HB16-v4.2",),
            snippet_keys=("hb16",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bgColor": "#00175A",
                "textColor": "#FFFFFF",
                "imageUrl": PLACEHOLDER_620X320,
                "headline": "Experiencia destacada",
                "description": "Completá este bloque con el texto final cuando esté disponible.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
            },
        ),
        "B05": ComponentDefinition(
            api_id="B05",
            slot="body",
            compose_type="single",
            source_ids=("HB18-v4.2",),
            snippet_keys=("hb18",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bg_color": "#00175A",
                "text_color": "#00175A",
                "image_url": PLACEHOLDER_620X320,
                "headline": "Headline card",
                "subheadline": "Subheadline por defecto",
            },
        ),
        "B06": ComponentDefinition(
            api_id="B06",
            slot="body",
            compose_type="single",
            source_ids=("HB21-v4.2",),
            snippet_keys=("hb21",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bgColor": "#00175A",
                "accentColor": "#006FCF",
                "textColor": "#00175A",
                "imageUrl": PLACEHOLDER_620X620,
                "headlineTop": "SEGUINOS",
                "headlineAccent": "en Instagram.",
                "description": "Usá este bloque como campaña cuadrada o reemplazá los datos por los definitivos.",
            },
        ),
        "B07": ComponentDefinition(
            api_id="B07",
            slot="body",
            compose_type="single",
            source_ids=("IM03-v4.2",),
            snippet_keys=("im03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            context_builder="paired_items",
            defaults={
                "ctaLabel": "Conocé más",
                "items": (
                    {
                        "title": "Producto 1",
                        "description": "Descripción del producto o beneficio.",
                        "badge": "Nuevo",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "Conocé más",
                    },
                    {
                        "title": "Producto 2",
                        "description": "Descripción del producto o beneficio.",
                        "badge": "Destacado",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "Conocé más",
                    },
                ),
            },
        ),
        "B08": ComponentDefinition(
            api_id="B08",
            slot="body",
            compose_type="single",
            source_ids=("TM01-v4.2",),
            snippet_keys=("tm01",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "headline": "Título del módulo",
                "description": "Texto descriptivo por defecto.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
                "buttonColor": "#006FCF",
                "buttonTextColor": "#FFFFFF",
            },
        ),
        "B09": ComponentDefinition(
            api_id="B09",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            defaults={
                "bgColor": "#EBECED",
                "headline": "Beneficio destacado",
                "offerCode": "AMEX",
                "description": "Texto del módulo TM04 por defecto.",
            },
        ),
        "B10": ComponentDefinition(
            api_id="B10",
            slot="body",
            compose_type="single",
            source_ids=("TM17-v4.2",),
            snippet_keys=("tm17",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            context_builder="benefit_cards",
            defaults={
                "accentColor": "#006FCF",
                "headline": "Beneficios destacados",
                "buttonLabel": "Ver más",
                "buttonUrl": "https://www.americanexpress.com/",
                "cards": (
                    {"title": "Beneficio 1", "subtitle": "Descripción breve", "iconUrl": PLACEHOLDER_60},
                    {"title": "Beneficio 2", "subtitle": "Descripción breve", "iconUrl": PLACEHOLDER_60},
                ),
            },
        ),
        "B11": ComponentDefinition(
            api_id="B11",
            slot="body",
            compose_type="single",
            source_ids=("TM03-v4.2",),
            snippet_keys=("tm03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.2",),
            context_builder="tm03_triptych",
            defaults={
                "bgColor": "#00175A",
                "headlineColor": "#FFFFFF",
                "dividerColor": "#0960c4",
                "headlineHtml": "Adem&aacute;s, este mes disfrut&aacute; de <strong style=\"font-family: HelveticaNeue, Helvetica Neue Regular, Helvetica, Arial, sans-serif;\">beneficios en hoteles.</strong>",
                "disclaimerHtml": "No acumulable con otras promociones.<br class=\"mobile-on\" style=\"display:none;\"> Pueden aplicar restricciones. Aplican fechas de veda.",
                "step1LinkUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step1ImageUrl": PLACEHOLDER_60,
                "step1ImageAlt": "Beneficio 1",
                "step1ImageWidth": "97",
                "step1DescriptionHtml": "sin tope y en el acto <br> en hoteles seleccionados",
                "step1CtaUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step1CtaLabel": "M&aacute;s informaci&oacute;n",
                "step2LinkUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step2ImageUrl": PLACEHOLDER_60,
                "step2ImageAlt": "Beneficio 2",
                "step2ImageWidth": "93",
                "step2DescriptionHtml": "Alojate 3 noches y obten&eacute; <br> una noche extra de regalo <br> en hoteles seleccionados",
                "step2CtaUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step2CtaLabel": "M&aacute;s informaci&oacute;n",
                "step3LinkUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step3ImageUrl": PLACEHOLDER_60,
                "step3ImageAlt": "Beneficio 3",
                "step3ImageWidth": "100",
                "step3DescriptionHtml": "sin tope y en el acto",
                "step3LogoUrl": "",
                "step3LogoAlt": "",
                "step3LogoWidth": "107",
                "step3CtaUrl": "https://www.americanexpress.com/es-ar/beneficios/promociones/",
                "step3CtaLabel": "M&aacute;s informaci&oacute;n",
            },
        ),
        "B12": ComponentDefinition(
            api_id="B12",
            slot="body",
            compose_type="single",
            source_ids=("HB18-v4.2",),
            snippet_keys=("hb18_merchant_shot_travel_agst25",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B13": ComponentDefinition(
            api_id="B13",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_travel_agst25_agencias",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B14": ComponentDefinition(
            api_id="B14",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_travel_agst25_compras",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B15": ComponentDefinition(
            api_id="B15",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_travel_agst25_spa",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B16": ComponentDefinition(
            api_id="B16",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_travel_agst25_hashtag",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B17": ComponentDefinition(
            api_id="B17",
            slot="body",
            compose_type="single",
            source_ids=("TM03-v4.2",),
            snippet_keys=("tm03_merchant_shot_travel_agst25",),
            repeatable=True,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B18": ComponentDefinition(
            api_id="B18",
            slot="body",
            compose_type="single",
            source_ids=("HB03-v4.2",),
            snippet_keys=("hb03_merchant_newsletter_dic25",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B19": ComponentDefinition(
            api_id="B19",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_newsletter_dic25_intro",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B20": ComponentDefinition(
            api_id="B20",
            slot="body",
            compose_type="single",
            source_ids=("TM01-v4.2",),
            snippet_keys=("tm01_merchant_newsletter_dic25_compras",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B21": ComponentDefinition(
            api_id="B21",
            slot="body",
            compose_type="single",
            source_ids=("HB08-v4.2",),
            snippet_keys=("hb08_merchant_newsletter_dic25_compras",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B22": ComponentDefinition(
            api_id="B22",
            slot="body",
            compose_type="single",
            source_ids=("TM01-v4.2",),
            snippet_keys=("tm01_merchant_newsletter_dic25_gastronomia",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B23": ComponentDefinition(
            api_id="B23",
            slot="body",
            compose_type="single",
            source_ids=("HB08-v4.2",),
            snippet_keys=("hb08_merchant_newsletter_dic25_gastronomia",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B24": ComponentDefinition(
            api_id="B24",
            slot="body",
            compose_type="single",
            source_ids=("TM01-v4.2",),
            snippet_keys=("tm01_merchant_newsletter_dic25_hoteles",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B25": ComponentDefinition(
            api_id="B25",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_newsletter_dic25_hoteles",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B26": ComponentDefinition(
            api_id="B26",
            slot="body",
            compose_type="single",
            source_ids=("HB08-v4.2",),
            snippet_keys=("hb08_merchant_newsletter_dic25_hoteles",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B27": ComponentDefinition(
            api_id="B27",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_newsletter_dic25_cta",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B28": ComponentDefinition(
            api_id="B28",
            slot="body",
            compose_type="single",
            source_ids=("HB18-v4.2",),
            snippet_keys=("hb18_merchant_shot_deporte_dic25",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B29": ComponentDefinition(
            api_id="B29",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_deporte_dic25_intro",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B30": ComponentDefinition(
            api_id="B30",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_deporte_dic25_clubs",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B31": ComponentDefinition(
            api_id="B31",
            slot="body",
            compose_type="single",
            source_ids=("HB08-v4.2",),
            snippet_keys=("hb08_merchant_shot_deporte_dic25",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "B32": ComponentDefinition(
            api_id="B32",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.2",),
            snippet_keys=("tm04_merchant_shot_deporte_dic25_closing",),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "F01": ComponentDefinition(
            api_id="F01",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05-v4.2", "FM02", "FM03-v4.2", "FM04-v4.2"),
            snippet_keys=("fm05", "fm02", "fm03", "fm04"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "instagramImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-instagram.png",
                "facebookImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-facebook.png",
                "youtubeImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-youtube.png",
                "taglineDesktopUrl": PLACEHOLDER_TAGLINE_WIDE,
                "taglineMobileUrl": PLACEHOLDER_TAGLINE_WIDE_MOBILE,
                "legalHtml": DEFAULT_LEGAL_HTML,
            },
        ),
        "F03": ComponentDefinition(
            api_id="F03",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05-v4.2", "FM02", "FM03-v4.2", "FM04-v4.2"),
            snippet_keys=("fm05", "fm02", "fm03", "fm04_merchant_shot_travel_agst25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "instagramImg": "https://mailing.design/amex/CORP-Shot-Travel-Agst25/images/1908-CORP-Shot-Travel-Agst25_26.png",
                "facebookImg": "https://mailing.design/amex/CORP-Shot-Travel-Agst25/images/1908-CORP-Shot-Travel-Agst25_27.png",
                "youtubeImg": "https://mailing.design/amex/CORP-Shot-Travel-Agst25/images/1908-CORP-Shot-Travel-Agst25_28.png",
                "taglineDesktopUrl": "https://i.email.americanexpress.com/wpm/1288/Images/1908-MERCHANT-Shot-Travel-Agst25_25a.jpg",
                "taglineMobileUrl": "https://i.email.americanexpress.com/wpm/1288/Images/1908-MERCHANT-Shot-Travel-Agst25_25mbl.jpg",
            },
        ),
        "F04": ComponentDefinition(
            api_id="F04",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05-v4.2", "FM02", "FM03-v4.2", "FM04-v4.2"),
            snippet_keys=("fm05", "fm02_merchant_newsletter_dic25", "fm03", "fm04_merchant_newsletter_dic25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={
                "instagramImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-instagram.png",
                "facebookImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-facebook.png",
                "youtubeImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-youtube.png",
                "taglineDesktopUrl": "https://i.email.americanexpress.com/wpm/1288/Images/271125_MERCHANT-Newsletter-Dic25_20.jpg",
                "taglineMobileUrl": "https://i.email.americanexpress.com/wpm/1288/Images/271125_MERCHANT-Newsletter-Dic25_20mbl.jpg",
            },
        ),
        "F05": ComponentDefinition(
            api_id="F05",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05-v4.2", "FM02", "FM03-v4.2", "FM04-v4.2"),
            snippet_keys=("fm05_merchant_shot_deporte_dic25", "fm02_merchant_shot_deporte_dic25", "fm03", "fm04_merchant_shot_deporte_dic25"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            defaults={},
        ),
        "F02": ComponentDefinition(
            api_id="F02",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05-v4.2", "FM01-v4.2", "TM06-v4.2", "FM02", "FM03-v4.2", "FM04-v4.2"),
            snippet_keys=("fm05", "fm01", "tm06", "fm02", "fm03", "fm04"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.2",),
            context_builder="cross_sell_icons",
            defaults={
                "crossSellTitle": "Más beneficios",
                "crossSellItems": (),
                "instagramImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-instagram.png",
                "facebookImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-facebook.png",
                "youtubeImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-youtube.png",
                "taglineDesktopUrl": PLACEHOLDER_TAGLINE_WIDE,
                "taglineMobileUrl": PLACEHOLDER_TAGLINE_WIDE_MOBILE,
                "legalHtml": DEFAULT_LEGAL_HTML,
            },
        ),
    }
)

MARIGOLD_V40_SNIPPETS = MappingProxyType(
    {
        "separator": _snippet("marigold-v4.0", "separator", "separator.html", "SEPARATOR"),
        "ph01": _snippet("marigold-v4.0", "ph01", "ph01.html", "PH01-v4.0"),
        "bp02": _snippet("marigold-v4.0", "bp02", "bp02.html", "BP02-v4.0"),
        "hb03": _snippet("marigold-v4.0", "hb03", "hb03.html", "HB03-v4.0"),
        "hb15": _snippet("marigold-v4.0", "hb15", "hb15.html", "HB15-v4.0"),
        "im02": _snippet("marigold-v4.0", "im02", "im02.html", "IM02-v4.0"),
        "tm04": _snippet("marigold-v4.0", "tm04", "tm04.html", "TM04-v4.0"),
        "fm05": _snippet("marigold-v4.0", "fm05", "fm05.html", "FM05"),
        "fm01": _snippet("marigold-v4.0", "fm01", "fm01.html", "FM01-v4.0"),
        "tm06": _snippet("marigold-v4.0", "tm06", "tm06.html", "TM06-v4.0"),
        "fm02": _snippet("marigold-v4.0", "fm02", "fm02.html", "FM02"),
        "fm03": _snippet("marigold-v4.0", "fm03", "fm03.html", "FM03-v4.0"),
        "fm04": _snippet("marigold-v4.0", "fm04", "fm04.html", "FM04-v4.0"),
    }
)

MARIGOLD_V40_COMPONENTS = MappingProxyType(
    {
        "H01": ComponentDefinition(
            api_id="H01",
            slot="header",
            compose_type="composite",
            source_ids=("PH01-v4.0", "BP02-v4.0"),
            snippet_keys=("ph01", "bp02"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.0",),
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
                "logoUrl": PLACEHOLDER_60,
                "taglineUrl": PLACEHOLDER_TAGLINE,
                "taglineAlt": "American Express",
                "cardImageUrl": PLACEHOLDER_80,
                "cardImageAlt": "American Express Card",
                "accountSuffix": "{(LAST_5)}",
                "greetingName": "{(FNAME)}",
                "memberSince": "{(MEMBER_SINCE)}",
                "loginLabel": "Mi cuenta",
                "loginUrl": "https://www.americanexpress.com/es-ar/account/login?email_consumer",
            },
        ),
        "B01": ComponentDefinition(
            api_id="B01",
            slot="body",
            compose_type="single",
            source_ids=("HB03-v4.0",),
            snippet_keys=("hb03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.0",),
            defaults={
                "bgColor": "#00175A",
                "textColor": "#FFFFFF",
                "imageUrl": PLACEHOLDER_620X320,
                "headline": "Más beneficios para tu tarjeta",
                "description": "Bloque por defecto para hero v4.0.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
            },
        ),
        "B02": ComponentDefinition(
            api_id="B02",
            slot="body",
            compose_type="single",
            source_ids=("HB15-v4.0",),
            snippet_keys=("hb15",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.0",),
            defaults={
                "imageUrl": PLACEHOLDER_620X320,
                "headline": "Extendimos tu límite de crédito.",
                "description": "Texto por defecto para HB15 v4.0.",
            },
        ),
        "B03": ComponentDefinition(
            api_id="B03",
            slot="body",
            compose_type="single",
            source_ids=("IM02-v4.0",),
            snippet_keys=("im02",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("marigold-v4.0",),
            defaults={
                "imageUrl": PLACEHOLDER_305X200,
                "headline": "Beneficio destacado",
                "description": "Descripción por defecto para IM02 v4.0.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "Conocé más",
            },
        ),
        "B04": ComponentDefinition(
            api_id="B04",
            slot="body",
            compose_type="single",
            source_ids=("TM04-v4.0",),
            snippet_keys=("tm04",),
            repeatable=True,
            compatible_families=("marigold-v4.0",),
            defaults={"headline": "Beneficio destacado", "description": "Texto por defecto para TM04 v4.0."},
        ),
        "F01": ComponentDefinition(
            api_id="F01",
            slot="footer",
            compose_type="composite",
            source_ids=("FM05", "FM01-v4.0", "TM06-v4.0", "FM02", "FM03-v4.0", "FM04-v4.0"),
            snippet_keys=("fm05", "fm01", "tm06", "fm02", "fm03", "fm04"),
            required_props=(),
            repeatable=False,
            compatible_families=("marigold-v4.0",),
            context_builder="cross_sell_icons",
            defaults={
                "taglineMobileUrl": "",
                "crossSellTitle": "Más beneficios",
                "crossSellItems": (),
                "instagramImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-instagram.png",
                "facebookImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-facebook.png",
                "youtubeImg": "https://www.americanexpress.com/content/dam/amex/ar/staticassets/email/social-youtube.png",
                "taglineDesktopUrl": PLACEHOLDER_TAGLINE_WIDE,
                "legalHtml": DEFAULT_LEGAL_HTML,
            },
        ),
    }
)

CENTURION_SNIPPETS = MappingProxyType(
    {
        "separator": _snippet("centurion-1.0", "separator", "separator.html", "SEPARATOR"),
        "ph01": _snippet("centurion-1.0", "ph01", "ph01.html", "PH01"),
        "bp01": _snippet("centurion-1.0", "bp01", "bp01.html", "BP01"),
        "chb01": _snippet("centurion-1.0", "chb01", "chb01.html", "CHB01"),
        "ctm03": _snippet("centurion-1.0", "ctm03", "ctm03.html", "CTM03"),
        "cim02": _snippet("centurion-1.0", "cim02", "cim02.html", "CIM02"),
        "cim03": _snippet("centurion-1.0", "cim03", "cim03.html", "CIM03"),
        "cim05": _snippet("centurion-1.0", "cim05", "cim05.html", "CIM05"),
        "tm06": _snippet("centurion-1.0", "tm06", "tm06.html", "TM06"),
        "cfm01": _snippet("centurion-1.0", "cfm01", "cfm01.html", "CFM01"),
        "cfm02": _snippet("centurion-1.0", "cfm02", "cfm02.html", "CFM02"),
        "ctm14": _snippet("centurion-1.0", "ctm14", "ctm14.html", "CTM14"),
        "cfm03": _snippet("centurion-1.0", "cfm03", "cfm03.html", "CFM03"),
    }
)

CENTURION_COMPONENTS = MappingProxyType(
    {
        "H01": ComponentDefinition(
            api_id="H01",
            slot="header",
            compose_type="composite",
            source_ids=("PH01", "BP01"),
            snippet_keys=("ph01", "bp01"),
            required_props=(),
            repeatable=False,
            compatible_families=("centurion-1.0",),
            defaults={
                "preheaderLabel": "PUBLICIDAD",
                "viewOnlineUrl": "https://x.email.americanexpress.com/ats/msg.aspx?sg1={(URLSignature1)}",
                "logoUrl": PLACEHOLDER_60,
                "taglineUrl": PLACEHOLDER_TAGLINE_DARK,
                "cardImageUrl": PLACEHOLDER_80,
                "accountSuffix": "{(LAST_5)}",
                "greetingName": "{(FULLNAME)}",
                "loginLabel": "Mi cuenta",
                "loginUrl": "https://www.americanexpress.com/es-ar/account/login?email_consumer",
                "memberSince": "{(MEMBER_SINCE)}",
            },
        ),
        "B01": ComponentDefinition(
            api_id="B01",
            slot="body",
            compose_type="single",
            source_ids=("CHB01",),
            snippet_keys=("chb01",),
            repeatable=True,
            compatible_families=("centurion-1.0",),
            defaults={
                "eyebrow": "EXCLUSIVO CENTURION",
                "imageUrl": PLACEHOLDER_620X250,
                "headline": "Experiencia Centurion",
                "description": "Contenido por defecto para el hero Centurion.",
                "ctaUrl": "https://www.americanexpress.com/",
                "ctaLabel": "CONOCER MÁS",
            },
        ),
        "B02": ComponentDefinition(
            api_id="B02",
            slot="body",
            compose_type="single",
            source_ids=("CTM03",),
            snippet_keys=("ctm03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("centurion-1.0",),
            defaults={
                "textColor": "#FFFFFF",
                "bgColor": "#000000",
                "headline": "Beneficio Centurion",
                "description": "Texto por defecto para CTM03.",
            },
        ),
        "B03": ComponentDefinition(
            api_id="B03",
            slot="body",
            compose_type="single",
            source_ids=("CIM02",),
            snippet_keys=("cim02",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("centurion-1.0",),
            context_builder="paired_items",
            defaults={
                "ctaLabel": "VER BENEFICIO",
                "items": (
                    {
                        "title": "Beneficio 1",
                        "description": "Descripción del beneficio.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "VER BENEFICIO",
                    },
                    {
                        "title": "Beneficio 2",
                        "description": "Descripción del beneficio.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "ctaUrl": "https://www.americanexpress.com/",
                        "ctaLabel": "VER BENEFICIO",
                    },
                ),
            },
        ),
        "B04": ComponentDefinition(
            api_id="B04",
            slot="body",
            compose_type="single",
            source_ids=("CIM03",),
            snippet_keys=("cim03",),
            repeatable=True,
            auto_separator_after="separator",
            compatible_families=("centurion-1.0",),
            context_builder="paired_items",
            defaults={
                "ctaLabel": "VER BENEFICIO",
                "items": (
                    {
                        "title": "Partner 1",
                        "description": "Descripción del partner.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "logoUrl": PLACEHOLDER_TAGLINE_DARK,
                    },
                    {
                        "title": "Partner 2",
                        "description": "Descripción del partner.",
                        "imageUrl": PLACEHOLDER_305X200,
                        "logoUrl": PLACEHOLDER_TAGLINE_DARK,
                    },
                ),
            },
        ),
        "B05": ComponentDefinition(
            api_id="B05",
            slot="body",
            compose_type="single",
            source_ids=("CIM05",),
            snippet_keys=("cim05",),
            repeatable=True,
            compatible_families=("centurion-1.0",),
            context_builder="benefit_cards",
            defaults={
                "accentColor": "#C9A84C",
                "headline": "Selección Centurion",
                "buttonLabel": "VER MÁS",
                "buttonUrl": "https://www.americanexpress.com/",
                "cards": (
                    {"title": "Beneficio 1", "subtitle": "Descripción breve", "iconUrl": PLACEHOLDER_60},
                    {"title": "Beneficio 2", "subtitle": "Descripción breve", "iconUrl": PLACEHOLDER_60},
                ),
            },
        ),
        "F01": ComponentDefinition(
            api_id="F01",
            slot="footer",
            compose_type="composite",
            source_ids=("TM06", "CFM01", "CFM02", "CTM14", "CFM03"),
            snippet_keys=("tm06", "cfm01", "cfm02", "ctm14", "cfm03"),
            required_props=(),
            repeatable=False,
            compatible_families=("centurion-1.0",),
            context_builder="cross_sell_icons",
            defaults={
                "crossSellTitle": "Beneficios Centurion",
                "crossSellItems": (),
                "legalHtml": DEFAULT_CENTURION_LEGAL_HTML,
            },
        ),
    }
)


FAMILIES = MappingProxyType(
    {
        "marigold-v4.2": FamilyDefinition(
            family_id="marigold-v4.2",
            shell_path=DATA_DIR / "shells" / "marigold-v4.2.html",
            shell_defaults={"subject": "AMEX", "outerBg": "#E0E0E0"},
            snippets=MARIGOLD_V42_SNIPPETS,
            components=MARIGOLD_V42_COMPONENTS,
        ),
        "marigold-v4.0": FamilyDefinition(
            family_id="marigold-v4.0",
            shell_path=DATA_DIR / "shells" / "marigold-v4.0.html",
            shell_defaults={"subject": "AMEX", "outerBg": "#D9D9D6"},
            snippets=MARIGOLD_V40_SNIPPETS,
            components=MARIGOLD_V40_COMPONENTS,
        ),
        "centurion-1.0": FamilyDefinition(
            family_id="centurion-1.0",
            shell_path=DATA_DIR / "shells" / "centurion-1.0.html",
            shell_defaults={"subject": "Centurion", "outerBg": "#000000"},
            snippets=CENTURION_SNIPPETS,
            components=CENTURION_COMPONENTS,
        ),
    }
)
